### ISSUE TITLE
JS Partials not being loaded in dev

### ISSUE THREAD

**Issue by rotavio** [aderaaij/totallystatical#2]
Loved your generator! Thanks!
I'm having a problem with the js files in development mode. Don't know if I'm missing something here.
I've created several .js files in the assets/js/partials folder, and ran only 'gulp' on command line.
As I understand from the gulp files, they should be joined in the scripts.js file, correct? For some reason this is nothing happening.
Do I nedd to do something else?

**Comment by aderaaij** [comment]
Hiya Rotavio, thanks for the love! I thought I was the only one using this, haha. 
The js files in the partial folder will not be automatically generated to the  script.js. Instead it leverages babel/es6 so you can do includes in the `src/assets/js/scripts.js`. For example, if you have a file named `slider.js` in your `src/assets/js/partials/` folder, you can import it in your `src/assets/js/scripts.js` by adding the line `import './partials/Helpers.js';`. 
I hope this makes sense and works, let me know if it doesn't.

Also, in this way you can import javascript packages installed through npm/yarn. For example, if you install the script Headroom.js through NPM you can add it to your script by adding the line `import Headroom from 'Headroom.js';` to your scripts.js.

**Comment by aderaaij** [comment]
@rotavio I'll close this issue for lack of activity. If I can help you with anything, please (re)open an issue or contact me!
