### ISSUE TITLE
Gulp Pretty URL's?

### ISSUE THREAD

**Issue by sananes** [aderaaij/totallystatical#3]
Hi, 

First of all fantastic work on this! I did have an issue to get this working to start. Anyways, I have a question. I would love the ability to have any page inside a folder to automatically build the same structure e.g. while also updating the url links in files to point to stylesheets and scripts from the root.

```
index.html
page1/index.html
page2/index.html
```

Am I missing something or is this already built in?

Sorry for my awful explanation...

EDIT: Okay I've managed to figure it out.

**Comment by aderaaij** [comment]
Glad you figured it out. Did you just put the .pug files in subdirectories? It's also possible to use a .htaccess file on the server to remove the .html and make the urls look pretty
