### ISSUE TITLE
Build:Production does not account for url swapping on images

### ISSUE THREAD

**Issue by sananes** [aderaaij/totallystatical#5]
Hey buddy,

Something I've noticed when doing a `gulp build:production` in terminal. The output directory does not account for renaming the src image files to revision naming on stylesheets.

**Comment by aderaaij** [comment]
Oh snap! I've not been using the file revisioning often (as I often use this as start of a WP theme or so and don't have need for cache busting) so It's been a while that this has a problem for me. I'll investigate and report back. Thx!

**Comment by aderaaij** [comment]
Okay the problem seems to be that the REV config is looking for the entire file path instead of just the file itself. So in the CSS `../img/image.jpg` will not be renamed, whereas `../../assets/img/image.jpg` will be renamed.

**Comment by aderaaij** [comment]
Okay, I Monkey patched the replacement of images assets in css files. Now `../img/` will be replaced by `../img/assets/`, the cachebusted version will be added and `../img/assets/` will be turned back to `../img/` again.

It's not the best solution as it only works for background images, always assumes the images are in the `img` folder and also assumes you don't put `"` or `'` around the image url. But for now it'll solve most usecases!
