### ISSUE TITLE
Need Update

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [aderaaij/totallystatical#9]
Please update totallystatical dependencies. We really need update.

**Comment by aderaaij** [comment]
Hi @ayoubkhan558 , I'll have a look! I haven't bothered with this project anymore because there are such great alternatives like Svelte, Eleventy and gatsbyJS. Maybe one of these projects would suit your needs better anyway?

**Comment by ayoubkhan558-zz** [comment]
> Hi @ayoubkhan558 , I'll have a look! I haven't bothered with this project anymore because there are such great alternatives like Svelte, Eleventy and gatsbyJS. Maybe one of these projects would suit your needs better anyway?

So then you need to archive this project, So developer don't waste their time here.

**Comment by aderaaij** [comment]
I'll consider it, thank you. In the meanwhile developers are very capable of deciding for themselves where they spend their time on. Also, your free to create a pull request, of course.
